name: Build & Release

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile binaries
        run: |
          make linux/amd64
      - name: Test
        run : |
          ls build/
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8 #t
        with:
          files: |
            build/**